[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/shell.html"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "public, max-age=3600"